services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - '3307:3306'

    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    # ports:
    #   - '6379:6379'

    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 3

  django:
    build: .
    container_name: django

    volumes:
      - ./django/startapp.sh:/startapp.sh
      - ./django/app:/app

    entrypoint: /startapp.sh

    environment:
      - DATABASE_URL=mysql://root:root@db:3306/appDB
      - PYTHONUNBUFFERED=1

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ['CMD', 'python', 'manage.py', 'check']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/src:/etc/nginx/html
      - ./nginx/staticfiles:/staticfiles
    ports:
      - '80:80'
    links:
      - db
